### ISSUE TITLE
My Devcard is not a valid SVG

### ISSUE THREAD

**Issue by irongut** [dailydotdev/action-devcard#119] opened 2022-03-03 18:57 UTC
My devcard has stopped showing on my profile in recent days. On investigation I discovered that the SVG is not valid, Firefox gives this error when I try to load the devcard itself:

```
XML Parsing Error: duplicate attribute
Location: https://raw.githubusercontent.com/irongut/irongut/master/devcard.svg
Line Number 154, Column 1033:
    <path transform="scale(5.2)" d="M8.50658984,14.611 L9.0669873,15.580127 C9.21720124,15.8403052 9.4388324,16.0444778 9.69901603,16.1736704 L8.14158984,18.999 L6.86158984,19 C6.58544746,19 6.36158984,18.7761424 6.36158984,18.5 C6.36158984,18.4129865 6.3842975,18.3274794 6.42746827,18.2519305 L8.50658984,14.611 Z M10.1376351,5 C10.2246769,5 10.310211,5.02272249 10.3857773,5.06592003 C10.5988758,5.18773797 10.6883289,5.44260963 10.6093253,5.66611793 L10.571715,5.74814226 L7.28153572,11.5037155 C7.18904327,11.6655143 7.14521691,11.8467056 7.15005663,12.0268841 L3.00018036,12.0268841 C2.99622748,11.7325006 3.05720438,11.4374403 3.18311107,11.163941 L3.26368,11.007431 L6.26591,5.75557323 C6.50872639,5.33080991 6.94150028,5.05390285 7.42253384,5.00706655 L7.56815,5 L10.1376351,5 Z M15.8593663,5 L14.300984,7.82632959 C14.1392482,7.74602068 13.9626152,7.69468507 13.7789793,7.67688046 L13.6339746,7.66987298 L12.4745898,7.669 L13.7120794,5.50386106 C13.8901222,5.19228606 14.2214657,5 14.5803225,5 L15.8593663,5 Z" id="Shine" id="" fill-opacity="0.2" fill="#F5F8FC" />
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
```

As you can see the problem is duplicate `id` attributes, the second of which is empty.

My profile repo: [irongut/irongut](https://github.com/irongut/irongut)
My current dev card: https://github.com/irongut/irongut/blob/f2665cc190bf138006f66fd935f437605cb7fb5e/devcard.svg (fetched 02/02/22 20:07 GMT)

**Comment by omBratteng** [comment] 2022-03-04 08:06
Duplicate of https://github.com/dailydotdev/daily/issues/491
@idoshamun, can you move the issue?

**Comment by idoshamun** [comment] 2022-03-04 22:08
Should be fixed now anyway :)

**Closed by idoshamun** 2022-03-04 22:08 UTC
